title: Melissa Bell Personal Website
description: This is my personal website for analytics work I have done in my Competing Through Business Analytics Course at the College of William and Mary.
google_analytics:
theme: jekyll-theme-modernist
